posts/urls.py
from django.urls import path
from .views import (
    post_comment_create_and_list_view,
    like_unlike_post,
    PostDeleteView,
    PostUpdateView,
    create_post,
)


app_name = 'posts'
urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('create-post/', create_post, name='create-post'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    invites_received_view,
    invite_profiles_list_view,
    Profiles_list_view,
    ProfileDetailView,
    send_invatation,
    remove_from_friends,
    accept_invatation,
    reject_invatation,
)

app_name = 'profiles'

urlpatterns = [
    path('', Profiles_list_view.as_view(), name='all-profiles-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/accept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
]

social_cloud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/main/home.html
{% extends 'base.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}



<div class="first">
    <img src="https://cdn.discordapp.com/attachments/802608908140675092/864076822261137438/-1987987.jpg" width="700px" class="photo-first-page">
    <h4 class="first-text">За простой вещью может скрываться что-то <div class="word-1">большее</div></h4>
</div>


<div style="clear: left"></div>


<div class="second">
    <div class="second-text-block">
        <p>
            <img class="photo-second-page" src="https://cdn.discordapp.com/attachments/802608908140675092/864097704145059860/-112345678765432.jpg" width="700px">
            Скоро у нас появится Android и IOS приложение для удобного общения.
            <hr noshade size="4">
        </p>
    </div>
</div>


<br><br><br><br><br><br><br>


<div class="third">
    <img src="https://static.djangoproject.com/img/fundraising-heart.cd6bb84ffd33.svg" width="500px" class="photo-first-page">
    <h4 class="third-text">Совсем скоро у нас будет конкурс на самого активного пользователя</h4>
    <h1 class="konkurs">Узнать больше</h1>
</div>


<div style="clear: left"></div>
<br><br><br><br><br><br><br><br><br><br><br><br>


<div class="forth">
    <div class="text-block">
        <p class="f-block-info">
            <img class="photo-second2-page" src="https://cdn.discordapp.com/attachments/802608908140675092/864125070628487168/tree.jpg" width="800px">
            ForestChill - это место, где не надо выставлять себя на показ. Надо открыто делиться полезной и интересной информацией :)
            <hr noshade size="1">
        </p>
    </div>
</div>

<div style="clear: left"></div>
<div style="clear: right"></div>
<footer>
    <h4 class="foot-el">о нас</h4>
    <h4 class="foot-el">задонатить</h4>
    <h4 class="foot-el">чиллить</h4>
    <h4 class="foot-el">поддержка</h4>
    <h4 class="foot-el">онлайн игра</h4>
    <img src="https://cdn.discordapp.com/attachments/769529626610368522/863343768748687360/unknown.png" width="200px" class="foot-logo">

</footer>

{% endblock content %}

{% block scripts %}
<script>
$(window).scroll(function(){
if($(window).scrollTop > $('.elem').offset().top){
// показать нужный объект
}
})
</script>
{% endblock scripts %}

templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}
{% url 'posts:create-post' as path_to_create_post %}

<!-- NAME Forest Camp-->

<div class="header">
    <a href="/">
  <img src="https://cdn.discordapp.com/attachments/769529626610368522/863343768748687360/unknown.png" width="80px" class="logo">
        </a>
  <ul>
    <li><h4><a href="{{path_to_posts}}">посты</a></h4></li>
    <li><h4><a href="">аккаунт</a></h4></li>
    <li><h4><a href="{{path_to_all_profiles}}">найти друга</a></h4></li>
    <li><h4><a href="{{path_to_my_invites}}">заявки в друзья</a></h4></li>
    <li><h4><a href="{{path_to_my_profile}}">настройки</a></h4></li>
    <li><h4><a href="{{path_to_create_post}}">Сделать пост</a></h4></li>
    <li>
    {% if request.user.is_authenticated %}
    <div class="user-nav">
    <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
    <!--
      <div class="avatar-nav"><img src={{picture.url}} class="ui avatar image">&nbsp;
        <h6 class="username-nav">{{ request.user }}</h6>
      </div>
    -->
            </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                <h4 class="logout-button">logout</h4>
            </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="ui item">
          <h4 class="logout-button">login</h4>
            </a>
        {% endif %}
    </li>
</div>
  </ul>

</div>


<!--
<div class="header">
  <div class="container">
    <a href="{{path_to_home}}"><h1 class="name-company">Abracon_Wireless</h1></a>

  </div>
</div>

<nav class="nav" align="right">
  <input class="nav__check" type="checkbox" id="showmenu"/>
  <label class="nav__showmenu" for="showmenu">&#9776;</label>
  <label class="nav__back" for="showmenu"></label>
  <ul class="menu">
    <li><a class="menu__item" href="#">На главную</a></li>
    <li>
      <a class="menu__item" href="#">Посты</a>
      <input class="menu__check" type="checkbox" id="menu2">
      <label class="menu__showsub" for="menu2">&#9660;</label>
      <ul class="menu__submenu">
        <li><a class="menu__item" href="#">Профиль</a></li>
        <li><a class="menu__item" href="#">Пользователт</a></li>
      </ul>
    </li>
    <li><a class="menu__item" href="#">О нас</a></li>
    <li><a class="menu__item" href="#">Контакты</a></li>
    <li><a class="menu__item" href="#">Новые друзья</a></li>
      <img src="https://cdn.discordapp.com/attachments/769529626610368522/863354142311055380/logo-burger.jpg" width="200px" class="logo">
  </ul>
</nav>
-->



<!--
<header>
    <img src="https://cdn.discordapp.com/attachments/769529626610368522/863343768748687360/unknown.png" width="60px" class="logo">
    <h1 class="name-company"></h1>

</header>
-->

<!--
<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>Abracon Wireless</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Posts
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>

                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Invites &nbsp;&nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>


            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui avatar image">&nbsp;
                 {{ request.user }}
            </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>
-->

<br>